### PR TITLE
fixed explicit window usage

### PR DESCRIPTION
**Pull request by bad5anta**
I've been trying to use this client in React Native project, and this is a single line which stopped me from using it. When fixed - it works perfect, thanks!

### CODE REVIEW

**Comment by thetutlage** [comment]
Not meant to be used with react-native.

I can decided whether or not go with the PR, if I know whether the Websocket implementation of React native is same as the browser?

**Comment by slampenny** [comment]
If adding React-Native support is as easy as changing two lines, this has my vote.

We're also writing a react native project with adonis. If you're aiming to have wide support for this framework (and it seems like you are), you're going to have to support mobile development, and react-native is a huge growth area in mobile right now.

**Comment by thetutlage** [comment]
@slampenny 

Yes I do want framework to be adopted widely. But I am not sure if changing 2 lines is the correct solution to the problem.

Just like `react-native`, `Android` and `iOS native SDK's` are also used widely in mobile development and I do want clients for them too.

As I mentioned in this comment https://github.com/adonisjs/adonis-websocket-client/issues/45#issuecomment-394621429, I am not sure what's the correct way to use Browser libraries in react-native. So it will be great, if someone can produce some documents around same.

Also if we need a separate client for React native, Android and iOS, I am happy for those too.

**Comment by bad5anta** [comment]
@thetutlage it was the only explicit usage of `window` (which isn't available in React Native) and I've removed it as workaround only. Among it, for sure, it's better to have ability to pass ws protocol via options. In other places of code, there are checks for `window` presence in global scope, so it's fine in React Native

**Comment by thetutlage** [comment]
Does Websocket implementation of react-native on iOS and Android is compatible with the browser?

When I say implementation, it's not about the availability of `window`, but instead how packets are formed, sent and received over the TCP connection.

In short, the API has to be compatible with https://developer.mozilla.org/en-US/docs/Web/API/WebSocket.

**Comment by duyluonglc** [comment]
As their document I think react-native supports the websocket
https://facebook.github.io/react-native/docs/network#websocket-support
But I dont know how to do some actions like: subscribe, getSubscribe, connect using jwt token...

My dirty way is run a script to patch `adonisjs-websocket-client` after install package
```sh
#!/bin/sh
s1="var wsProtocol \= window\.location\.protocol \=\=\= 'https:' \? 'wss' : 'ws';" && 
s2="var wsProtocol \= window\.location \&\& window\.location\.protocol \=\=\= 'https:' \? 'wss' : 'ws';" && 
sed -i -e "s/$s1/$s2/g" node_modules/@adonisjs/websocket-client/dist/Ws.browser.js
```
So I can use `adonisjs-websocket-client` with react-native projects

**Comment by thetutlage** [comment]
@duyluonglc Thanks for sharing the link. Now since I know that they support the standard protocol, I can go ahead and fix this repo to work seamlessly with React native

**Comment by floristenhove** [comment]
Are there any updates on this? I'm thinking of using AdonisJS for the API for a React Native chat app and would like to know if I can use it. Keep up the good work!

**Comment by Matgsan** [comment]
Any updates? I developed all the backend logic for the chat and when i went to implement on React-Native i got that error. Serious each one that needs to implement with RN will need to fork and fix by themselves?

**Review by RomainLanz — APPROVED** [review]

**Comment by FrenchMajesty** [comment]
Sad that this issue dating back to 2018 is still not resolved. I am now dealing with this problem and this PR would be gladly welcomed.

**Comment by juniorsnts** [comment]
Alguém tem alguma solução?

**Comment by Matgsan** [comment]
@thetutlage Can you please review this? I feel there is a lot of people wanting this.

**Comment by joelpiccoli** [comment]
We're building an app for an internacional trading company and the adonis fits perfectly as our backend solution, but we also need realtime and we would prefer to avoid thrid part solutions for this problem, for a matter of escalability. This PR would help us a lot! Please, review this!

**Comment by migueldaipre** [comment]
+1

**Comment by lucascardial** [comment]
+1

**Pull request merged**
