### PR TITLE
fix(connection): fix connection crash when use without web browser

### PR DESCRIPTION
**Pull request by duyluonglc**
Hi @thetutlage 
I have issue when use websocket-client with react-native. After check your code
`const wsProtocol = window.location.protocol === 'https:' ? 'wss' : 'ws'`
location is undefined because it's not call from web browser.
This PR will fix this issue
Please check when avaialbe

### CODE REVIEW

**Comment by thetutlage** [comment]
This is just a patch on a short circuit.

The fix should be to stop booting ws client when rendered server side.

I don’t do SSR much, so I am not sure, if there’s a proper way to detect the running environment and add conditionals on basis of that

**Comment by thetutlage** [comment]
Okay my bad, you wrote `react-native` and not `ssr`. If you are not in a browser, I don't think it will infact work.

The `websocket-client` relies on the web browser implementation of sockets, so it will fail anyways

**Comment by duyluonglc** [comment]
Seem the test script failed :(
But I checked with react-native and the websocket works good after remove `window.location.protocol` from dist file. 
Can we detect `window.location` exists before assign?
`const wsProtocol = window.location ? (window.location.protocol === 'https:' ? 'wss' : 'ws') : ''`

**Comment by thetutlage** [comment]
Duplicate of https://github.com/adonisjs/adonis-websocket-client/pull/42

**Pull request closed without merging**
